### ISSUE TITLE
Matrix seems to be missing a "reflect" method

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-Content-raku#11]
My matrix algebra is very sketchy now since I haven't had to use it in years. But I am trying to compose a reflection followed by a rotation for a special method where a scaling followed or preceeded by a rotation doesn't give the expected or desired results. I found a Wikipedia article entitled [Rotations and reflections in two dimensions](https://en.wikipedia.org/wiki/Rotations_and_reflections_in_two_dimensions) which mathematically composes the two required transformations into a single reflection.

## UPDATE

There is a slight difference in signs in the article versus those in Matrix.rakumod which seem to be whether a positive rotation is clockwise or counterclockwise. I am working on a PR. I've changed signs in my PR to go with the PDF::Content convention and the tests I've added seem to work.

**Comment by dwarring** [comment]
Merged with PR https://github.com/pdf-raku/PDF-Content-raku/pull/12
