### ISSUE TITLE
Needs to work on Windows (even without Harfbuzz if necessary)

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-Content-raku#18]
David, how can I help? Have you looked at the Windows PDF packages at [Chocolatey.org](https://community.chocolatey.org)? I see a version of Ghostscript there.

**Comment by dwarring** [comment]
Hi Tom,
Good point.

The Harfbuzz team supply a set of official DLLs https://harfbuzz.github.io/install-harfbuzz.html.

It would be good to get the HarfBuzz modules working on Windows. Particularly now that PDF::Content depends on it.

I'll get onto it soon.
- David

**Comment by dwarring** [comment]
I've been trying a simple experiment to link against the DLLS. Trying to get a call to `hb_version` to work on Windows.

hbtest.c:
```
#include <stdio.h>
void hb_version(int* major, int* minor, int* micro);

void hbtest(void) {
    int major=0, minor=0, micro=0;
    hb_version(&major, &minor, &micro);
    fprintf(stderr, "version is %02d.%0d2.%02d\n", major, minor, micro);
}
```

Makefile:
```
all : hbtest.dll

hbtest.dll : hbtest.obj
	gcc -shared -Lharfbuzz-win32 -o harfbuzz-win32/hbtest.dll hbtest.obj
	-llibharfbuzz-0

$(SRC)/hbtest.obj : hbtest.c
	gcc -I $(SRC) -c -o hbtest.obj hbtest.c
```

No luck so far. I'm coming to the conclusion that this may not be the right approach. I'm thinks that those DLLs are designed to be used with executables such as `hb-shape.exe`, which are also included.

**Comment by dwarring** [comment]
So back to the drawing board. PDF::Content installs for me, but PDF::Font::Loader doesn't because it has HarfBuzz as a dependency.

So all you can do on Windows at the moment is use core fonts.

**Comment by tbrowder** [comment]
Thanks for the update, David.

-Tom

**Comment by tbrowder** [comment]
Closing this.
