### ISSUE TITLE
Missing PDF operators equivalent to PostScripts'  'rlineto' and 'rmoveto'

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-Content-raku#22]
They would permit less use of .transform and .translate and pretty much complete the set of PDF equivalents of PostScript operators.

I'm working on a PR and have added operators with PDF codes 'rl' and 'rm'. Note they are not defined in the PDF ISO manual, at least as far as I can find. And now I remember early on missing those two operators. I figured there must be another way to do it, but I couldn't so just accepted that those very smart people know what they are doing.

But I also wonder about them when I see the phrase 'and/or' which has come creeping into formal writing, and I'm too old school not to let it bother me.

...

**Comment by tbrowder** [comment]
I give up for now--I need to complain to the PDF ISO people.

I think I have found a routine to get the current point, so I can
build my own methods for RMoveTo and RLineTo.

It would be nice to have it in the PDF ISO standard, but I don't see wasting my too-limited time chasing that.

Thanks, David.

**Comment by tbrowder** [comment]
Closing as not practical.

**Comment by tbrowder** [comment]
David, I'm opening this up again with another idea. I did see in the lower level code the parsing methods that **may** be able to be modified for the 'rl' and 'rm' non-PDF standard operators, but **ONLY** if it truly is feasible and you are willing to accept such a change.

**Comment by tbrowder** [comment]
I'm looking at the spec again for extensions or something similar...

**Comment by dwarring** [comment]
Tom, do you know about the `current-point` method? It can be used during path construction and returns the x,y position of the last `MoveTo`, `Rectangle`, `LineTo`, `CurveTo` or `ClosePath` operation.

**Comment by tbrowder** [comment]
Great, thanks! 

As I mentioned above I thought I had seen it deep in the code, but wasn't sure how to get it. I will definitely use it! 

But I still can't believe the two PS operators were left out of the PDF standard! Argh!

**Comment by tbrowder** [comment]
Closing this. Thanks.
