### ISSUE TITLE
Feature request: A single location for a hash of XObject form objects accessible from each pdf.page

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-Content-raku#24]
Currently, in order to create such a thing, the user has to:

+ use .page(0) to store forms
+ provide a reference to .page(0) for each subsequent new page

**Comment by dwarring** [comment]
The Adobe engineers actually considered this with the original design of PDF. Resources, including Fonts and XObjects are usually stored in the Pages Resources dictionary, but they can be stored further up the resources tree and inherited by multiple pages. Resources can be effectively scoped to multiple pages.

I've added support for this in PDF::Content 0.8.8 release. The following will set up global sharing of resources between pages

```raku
use PDF::Lite;
my PDF::Lite $pdf .= new;
$pdf.Pages.global-resources-scope = True;
```

Any pages you add after this will globally share fonts and XObjects. They will share the same resources dictionary and have the same keys for those resources.

See also t/pdf-page-tree.t

**Comment by tbrowder** [comment]
Wow, thanks, David!

BTW, today I filed an issue with Richard (@finanalyst) vis-a-vis 'rakudoc2pdf' and the project as I see it. I put in a DRAFT comment (for your approval) based on the discussion we had about it a few days ago (where you corrected me about the proper name for it). I'm having trouble finding the correct, link but I'll email it to you when I find it.
