### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by frithnanth** [pdf-raku/PDF-Content-raku#3]
I'm using raku v.2019.11 .
When I try to install PDF::Content I see this message:

> ===> Testing: PDF::Content:ver<0.3.0>:auth<github:p6-pdf>:api<PDF.1.7>
> [PDF::Content] # Failed test 'content with comments'
> [PDF::Content] # at t/ops.t line 235
> [PDF::Content] # expected: $("175 720 m \% MoveTo", "175 700 l \% LineTo", "300 800 400 720 v \% CurveToInitial", "h \% ClosePath", "S \% Stroke", "\% That's all#2665!")
> [PDF::Content] #      got: $("175 720 m \% MoveTo", "175 700 l \% LineTo", "300 800 400 720 v \% CurveToInitial", "h \% ClosePath", "S \% Stroke", "\% That's all♥!")
> [PDF::Content] # You failed 1 test of 109
> ===> Testing [FAIL]: PDF::Content:ver<0.3.0>:auth<github:p6-pdf>:api<PDF.1.7>

**Comment by dwarring** [comment]
@frithnanth 
PDF::Content had got out of step with PDF, which hadn't had a proper version bump.
Also made this a todo test for PDF < v.0.3.8.

Please upgrade PDF to 0.3.8, or PDF::Content to 0.3.1 to fix.
